package com.example.logointerpreterbeta.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF426834)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC3EFAD)
val onPrimaryContainerLight = Color(0xFF042100)
val secondaryLight = Color(0xFF426833)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC3EFAD)
val onSecondaryContainerLight = Color(0xFF042100)
val tertiaryLight = Color(0xFF00696C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF9CF1F3)
val onTertiaryContainerLight = Color(0xFF002021)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8FAF0)
val onBackgroundLight = Color(0xFF191D17)
val surfaceLight = Color(0xFFF8FAF0)
val onSurfaceLight = Color(0xFF191D16)
val surfaceVariantLight = Color(0xFFDCE5DC)
val onSurfaceVariantLight = Color(0xFF404943)
val outlineLight = Color(0xFF707972)
val outlineVariantLight = Color(0xFFC0C9C1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E312B)
val inverseOnSurfaceLight = Color(0xFFEFF2E7)
val inversePrimaryLight = Color(0xFFA8D293)
val surfaceDimLight = Color(0xFFD9DBD1)
val surfaceBrightLight = Color(0xFFF8FAF0)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F5EA)
val surfaceContainerLight = Color(0xFFEDEFE5)
val surfaceContainerHighLight = Color(0xFFE7E9DF)
val surfaceContainerHighestLight = Color(0xFFE1E4D9)

val primaryLightMediumContrast = Color(0xFF274B1A)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF587F48)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF274B1A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF587F47)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF004B4D)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF238183)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFFffbab1)
val onErrorLightMediumContrast = Color(0xFF370001)
val errorContainerLightMediumContrast = Color(0xFFff5449)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF8FAF0)
val onBackgroundLightMediumContrast = Color(0xFF191D17)
val surfaceLightMediumContrast = Color(0xFFF8FAF0)
val onSurfaceLightMediumContrast = Color(0xFF191D16)
val surfaceVariantLightMediumContrast = Color(0xFFDCE5DC)
val onSurfaceVariantLightMediumContrast = Color(0xFF3C453F)
val outlineLightMediumContrast = Color(0xFF58615B)
val outlineVariantLightMediumContrast = Color(0xFF747D76)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2E312B)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEFF2E7)
val inversePrimaryLightMediumContrast = Color(0xFFA8D293)
val surfaceDimLightMediumContrast = Color(0xFFD9DBD1)
val surfaceBrightLightMediumContrast = Color(0xFFF8FAF0)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF2F5EA)
val surfaceContainerLightMediumContrast = Color(0xFFEDEFE5)
val surfaceContainerHighLightMediumContrast = Color(0xFFE7E9DF)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE1E4D9)

val primaryLightHighContrast = Color(0xFF062900)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF274B1A)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF062900)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF274B1A)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF002728)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF004B4D)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF8FAF0)
val onBackgroundLightHighContrast = Color(0xFF191D17)
val surfaceLightHighContrast = Color(0xFFF8FAF0)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDCE5DC)
val onSurfaceVariantLightHighContrast = Color(0xFF1E2620)
val outlineLightHighContrast = Color(0xFF3C453F)
val outlineVariantLightHighContrast = Color(0xFF3C453F)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2E312B)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFCCF9B6)
val surfaceDimLightHighContrast = Color(0xFFD9DBD1)
val surfaceBrightLightHighContrast = Color(0xFFF8FAF0)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF2F5EA)
val surfaceContainerLightHighContrast = Color(0xFFEDEFE5)
val surfaceContainerHighLightHighContrast = Color(0xFFE7E9DF)
val surfaceContainerHighestLightHighContrast = Color(0xFFE1E4D9)

val primaryDark = Color(0xFFA8D293)
val onPrimaryDark = Color(0xFF153809)
val primaryContainerDark = Color(0xFF2B4F1E)
val onPrimaryContainerDark = Color(0xFFC3EFAD)
val secondaryDark = Color(0xFFA8D293)
val onSecondaryDark = Color(0xFF153809)
val secondaryContainerDark = Color(0xFF2B4F1E)
val onSecondaryContainerDark = Color(0xFFC3EFAD)
val tertiaryDark = Color(0xFF80D4D7)
val onTertiaryDark = Color(0xFF003738)
val tertiaryContainerDark = Color(0xFF004F51)
val onTertiaryContainerDark = Color(0xFF9CF1F3)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF11140F)
val onBackgroundDark = Color(0xFFE1E4DA)
val surfaceDark = Color(0xFF11140F)
val onSurfaceDark = Color(0xFFE1E4D9)
val surfaceVariantDark = Color(0xFF404943)
val onSurfaceVariantDark = Color(0xFFC0C9C1)
val outlineDark = Color(0xFF8A938C)
val outlineVariantDark = Color(0xFF404943)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E4D9)
val inverseOnSurfaceDark = Color(0xFF2E312B)
val inversePrimaryDark = Color(0xFF426834)
val surfaceDimDark = Color(0xFF11140F)
val surfaceBrightDark = Color(0xFF373A33)
val surfaceContainerLowestDark = Color(0xFF0C0F0A)
val surfaceContainerLowDark = Color(0xFF191D16)
val surfaceContainerDark = Color(0xFF1D211A)
val surfaceContainerHighDark = Color(0xFF282B24)
val surfaceContainerHighestDark = Color(0xFF32362F)

val primaryDarkMediumContrast = Color(0xFFACD797)
val onPrimaryDarkMediumContrast = Color(0xFF031B00)
val primaryContainerDarkMediumContrast = Color(0xFF739B61)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFACD797)
val onSecondaryDarkMediumContrast = Color(0xFFffffff)
val secondaryContainerDarkMediumContrast = Color(0xFF739B61)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFF84D9DB)
val onTertiaryDarkMediumContrast = Color(0xFF001A1B)
val tertiaryContainerDarkMediumContrast = Color(0xFF479DA0)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)

val errorDarkMediumContrast = Color(0xFF8c0009)
val onErrorDarkMediumContrast = Color(0xFFffffff)
val errorContainerDarkMediumContrast = Color(0xFFda342e)
val onErrorContainerDarkMediumContrast = Color(0xFFffffff)

val backgroundDarkMediumContrast = Color(0xFF11140F)
val onBackgroundDarkMediumContrast = Color(0xFFE1E4DA)
val surfaceDarkMediumContrast = Color(0xFF11140F)
val onSurfaceDarkMediumContrast = Color(0xFFFAFCF1)
val surfaceVariantDarkMediumContrast = Color(0xFF404943)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC4CDC5)
val outlineDarkMediumContrast = Color(0xFF9CA59D)
val outlineVariantDarkMediumContrast = Color(0xFF7C857E)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE1E4D9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF282B24)
val inversePrimaryDarkMediumContrast = Color(0xFF2C501F)
val surfaceDimDarkMediumContrast = Color(0xFF11140F)
val surfaceBrightDarkMediumContrast = Color(0xFF373A33)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0F0A)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191D16)
val surfaceContainerDarkMediumContrast = Color(0xFF1D211A)
val surfaceContainerHighDarkMediumContrast = Color(0xFF282B24)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF32362F)

val primaryDarkHighContrast = Color(0xFFF2FFE6)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFACD797)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFF2FFE6)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFACD797)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFEAFFFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF84D9DB)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF11140F)
val onBackgroundDarkHighContrast = Color(0xFFE1E4DA)
val surfaceDarkHighContrast = Color(0xFF11140F)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF404943)
val onSurfaceVariantDarkHighContrast = Color(0xFFF4FDF4)
val outlineDarkHighContrast = Color(0xFFC4CDC5)
val outlineVariantDarkHighContrast = Color(0xFFC4CDC5)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE1E4D9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF0E3104)
val surfaceDimDarkHighContrast = Color(0xFF11140F)
val surfaceBrightDarkHighContrast = Color(0xFF373A33)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0C0F0A)
val surfaceContainerLowDarkHighContrast = Color(0xFF191D16)
val surfaceContainerDarkHighContrast = Color(0xFF1D211A)
val surfaceContainerHighDarkHighContrast = Color(0xFF282B24)
val surfaceContainerHighestDarkHighContrast = Color(0xFF32362F)















